package com.qimian233.ztool.hook.modules.systemframework

import android.annotation.SuppressLint
import android.view.KeyEvent
import com.qimian233.ztool.data.keys.PreferenceKeys
import com.qimian233.ztool.data.keys.ScopeKeys
import com.qimian233.ztool.hook.base.SystemHookModule
import io.github.libxposed.api.XposedModuleInterface.SystemServerStartingParam

/**
 * Non-linear volume key ramping hook module.
 *
 * Stock behavior (see com.android.server.audio.AudioService in services.jar):
 * every volume key event — including each long-press repeat generated by the
 * input pipeline (~1 repeat / 50ms after ~500ms delay) — is forwarded by
 * PhoneWindowManager.dispatchDirectAudioEvent() to
 * AudioService.handleVolumeKey(), which adjusts the suggested stream by a
 * constant ±1 step. Holding a volume key therefore ramps at a constant rate.
 *
 * This hook intercepts AudioService.handleVolumeKey(KeyEvent, boolean, String,
 * String) *before* it runs and drops part of the repeated ACTION_DOWN events
 * according to KeyEvent.getRepeatCount() (a monotonic proxy for hold duration),
 * producing a slow-start-then-accelerate ramp:
 *
 *   repeat 0 (single press)          -> always pass, click semantics unchanged
 *   repeats 1..TIER_1 (~0.5-1.5s)    -> pass every 4th  (slow, ~5 steps/s)
 *   repeats TIER_1..TIER_2 (~3s)     -> pass every 2nd  (~10 steps/s)
 *   repeats beyond TIER_2            -> pass all        (~20 steps/s, stock)
 *
 * ACTION_UP and other key codes are always passed through, so the volume panel
 * show/dismiss logic and the mute key are unaffected. Pairs well with
 * [FineVolumeSteps] (150-step scale makes the early slow tier finer).
 */
@SuppressLint("PrivateApi", "DiscouragedPrivateApi")
class VolumeKeyNonlinearRamp : SystemHookModule() {

    override fun getModuleName(): String = PreferenceKeys.VOLUME_KEY_NONLINEAR.name

    override fun getTargetPackages(): Array<String> = arrayOf(ScopeKeys.ANDROID_SYSTEM.packageName)

    override fun handleSystemServerStarting(param: SystemServerStartingParam) {
        try {
            val audioServiceClass = param.classLoader.loadClass("com.android.server.audio.AudioService")
            val keyEventClass = KeyEvent::class.java
            val handleVolumeKey = findMethod(
                audioServiceClass,
                "handleVolumeKey",
                keyEventClass,
                java.lang.Boolean.TYPE,
                String::class.java,
                String::class.java
            )
            hookWithId(handleVolumeKey, HOOK_ID) { chain ->
                val keyEvent = chain.args[0] as? KeyEvent
                if (keyEvent != null && shouldSuppressRepeat(keyEvent)) {
                    // Drop this repeat: return without proceeding.
                    return@hookWithId null
                }
                chain.proceed()
            }
            logger.info("Successfully hooked AudioService.handleVolumeKey")
        } catch (t: Throwable) {
            logger.error("Failed to hook AudioService.handleVolumeKey", t)
        }
    }

    /**
     * Decides whether this volume key event is a repeated ACTION_DOWN that the
     * non-linear ramp wants to swallow.
     */
    private fun shouldSuppressRepeat(keyEvent: KeyEvent): Boolean {
        if (keyEvent.action != KeyEvent.ACTION_DOWN) return false
        val keyCode = keyEvent.keyCode
        if (keyCode != KeyEvent.KEYCODE_VOLUME_UP && keyCode != KeyEvent.KEYCODE_VOLUME_DOWN) return false
        val repeat = keyEvent.repeatCount
        if (repeat == 0) return false
        val modulo = when {
            repeat < TIER_1_REPEAT -> TIER_1_MODULO
            repeat < TIER_2_REPEAT -> TIER_2_MODULO
            else -> 1
        }
        return repeat % modulo != 0
    }

    companion object {
        private const val HOOK_ID = "volume_key_nonlinear_handle_volume_key"

        // Repeat cadence is ~50ms, so 20 repeats ≈ 1s of holding.
        private const val TIER_1_REPEAT = 20
        private const val TIER_2_REPEAT = 60
        private const val TIER_1_MODULO = 4
        private const val TIER_2_MODULO = 2
    }
}
