package com.qimian233.ztool.hook.modules.systemframework

import android.annotation.SuppressLint
import android.view.KeyEvent
import com.qimian233.ztool.data.keys.PreferenceKeys
import com.qimian233.ztool.data.keys.ScopeKeys
import com.qimian233.ztool.hook.base.SystemHookModule
import io.github.libxposed.api.XposedModuleInterface.SystemServerStartingParam

/**
 * Non-linear volume key ramping hook module.
 *
 * Stock behavior: every volume key event — including each long-press repeat
 * generated by the input pipeline (~1 repeat / 50ms after ~500ms delay) — is
 * forwarded by PhoneWindowManager (via IStatusBarService.handleSystemKey on
 * this ZUI ROM; via IAudioService.handleVolumeKey on AOSP-ish paths) to the
 * component that adjusts the stream by a constant ±1 step. Holding a volume
 * key therefore ramps at a constant rate.
 *
 * This hook intercepts both forwarding choke points *before* they run and
 * drops part of the repeated ACTION_DOWN events according to
 * KeyEvent.getRepeatCount() (a monotonic proxy for hold duration), producing
 * a slow-start-then-accelerate ramp:
 *
 *   repeat 0 (single press)          -> always pass, click semantics unchanged
 *   repeats 1..TIER_1 (~0.5-1.5s)    -> pass every 4th  (slow, ~5 steps/s)
 *   repeats TIER_1..TIER_2 (~3s)     -> pass every 2nd  (~10 steps/s)
 *   repeats beyond TIER_2            -> pass all        (~20 steps/s, stock)
 *
 * ACTION_UP and other key codes are always passed through, so the volume panel
 * show/dismiss logic and the mute key are unaffected. Pairs well with
 * [FineVolumeSteps] (150-step scale makes the early slow tier finer).
 */
@SuppressLint("PrivateApi", "DiscouragedPrivateApi")
class VolumeKeyNonlinearRamp : SystemHookModule() {

    override fun getModuleName(): String = PreferenceKeys.VOLUME_KEY_NONLINEAR.name

    override fun getTargetPackages(): Array<String> = arrayOf(ScopeKeys.ANDROID_SYSTEM.packageName)

    override fun handleSystemServerStarting(param: SystemServerStartingParam) {
        val classLoader = param.classLoader
        hookKeyQueueDiagnostic(classLoader)
        hookStatusBarForward(classLoader)
        hookAudioServiceForward(classLoader)
    }

    /**
     * Temporary diagnostic: log every volume-related key event reaching
     * PhoneWindowManager.interceptKeyBeforeQueueing (the system_server entry
     * for all key events, repeats included) to trace where repeats are consumed.
     */
    private fun hookKeyQueueDiagnostic(classLoader: ClassLoader) {
        try {
            val pwmClass = classLoader.loadClass("com.android.server.policy.PhoneWindowManager")
            val intercept = findMethod(pwmClass, "interceptKeyBeforeQueueing", KeyEvent::class.java, Int::class.javaPrimitiveType)
            hookWithId(intercept, QUEUE_DIAG_HOOK_ID) { chain ->
                val keyEvent = chain.args[0] as? KeyEvent
                if (keyEvent != null) {
                    val keyCode = keyEvent.keyCode
                    if (keyCode == KeyEvent.KEYCODE_VOLUME_UP ||
                        keyCode == KeyEvent.KEYCODE_VOLUME_DOWN ||
                        keyCode == KeyEvent.KEYCODE_VOLUME_MUTE
                    ) {
                        val result = chain.proceed()
                        logger.debug(
                            "ikbq: action=${if (keyEvent.action == KeyEvent.ACTION_DOWN) "DOWN" else "UP"}" +
                                " code=$keyCode repeat=${keyEvent.repeatCount}" +
                                " flags=0x${Integer.toHexString(keyEvent.flags)}" +
                                " result=$result"
                        )
                        return@hookWithId result
                    }
                }
                chain.proceed()
            }
            logger.info("Successfully hooked PhoneWindowManager.interceptKeyBeforeQueueing (diagnostic)")
        } catch (t: Throwable) {
            logger.error("Failed to hook interceptKeyBeforeQueueing diagnostic", t)
        }
    }

    /**
     * Primary path on this ZUI ROM: PWM sends volume keys to SystemUI via
     * StatusBarManagerService.handleSystemKey(); the KeyEvent still carries
     * repeatCount, and suppressing here stops SystemUI from adjusting.
     */
    private fun hookStatusBarForward(classLoader: ClassLoader) {
        try {
            val statusBarServiceClass = classLoader.loadClass("com.android.server.statusbar.StatusBarManagerService")
            val handleSystemKey = findMethod(statusBarServiceClass, "handleSystemKey", KeyEvent::class.java)
            hookWithId(handleSystemKey, STATUS_BAR_HOOK_ID) { chain ->
                val keyEvent = chain.args[0] as? KeyEvent
                if (keyEvent == null) {
                    chain.proceed()
                    return@hookWithId null
                }
                if (shouldSuppressRepeat(keyEvent)) {
                    // Drop this repeat: return without proceeding.
                    logDecision(keyEvent, suppressed = true, before = -1, after = -1)
                    return@hookWithId null
                }
                val before = currentMusicVolumeIndex()
                chain.proceed()
                logDecision(keyEvent, suppressed = false, before = before, after = currentMusicVolumeIndex())
            }
            logger.info("Successfully hooked StatusBarManagerService.handleSystemKey")
        } catch (t: Throwable) {
            logger.error("Failed to hook StatusBarManagerService.handleSystemKey", t)
        }
    }

    /**
     * Fallback path (AOSP-style, e.g. TV routing / in-call variants):
     * AudioService.handleVolumeKey.
     */
    private fun hookAudioServiceForward(classLoader: ClassLoader) {
        try {
            val audioServiceClass = classLoader.loadClass("com.android.server.audio.AudioService")
            val handleVolumeKey = findMethod(
                audioServiceClass,
                "handleVolumeKey",
                KeyEvent::class.java,
                java.lang.Boolean.TYPE,
                String::class.java,
                String::class.java
            )
            hookWithId(handleVolumeKey, AUDIO_HOOK_ID) { chain ->
                val keyEvent = chain.args[0] as? KeyEvent
                if (keyEvent == null) {
                    chain.proceed()
                    return@hookWithId null
                }
                if (shouldSuppressRepeat(keyEvent)) {
                    logDecision(keyEvent, suppressed = true, before = -1, after = -1)
                    return@hookWithId null
                }
                val before = currentMusicVolumeIndex()
                chain.proceed()
                logDecision(keyEvent, suppressed = false, before = before, after = currentMusicVolumeIndex())
            }
            logger.info("Successfully hooked AudioService.handleVolumeKey")
        } catch (t: Throwable) {
            logger.error("Failed to hook AudioService.handleVolumeKey", t)
        }
    }

    /**
     * Decides whether this volume key event is a repeated ACTION_DOWN that the
     * non-linear ramp wants to swallow.
     */
    private fun shouldSuppressRepeat(keyEvent: KeyEvent): Boolean {
        if (keyEvent.action != KeyEvent.ACTION_DOWN) return false
        val keyCode = keyEvent.keyCode
        if (keyCode != KeyEvent.KEYCODE_VOLUME_UP && keyCode != KeyEvent.KEYCODE_VOLUME_DOWN) return false
        val repeat = keyEvent.repeatCount
        if (repeat == 0) return false
        val modulo = when {
            repeat < TIER_1_REPEAT -> TIER_1_MODULO
            repeat < TIER_2_REPEAT -> TIER_2_MODULO
            else -> 1
        }
        return repeat % modulo != 0
    }

    /**
     * Debug log of one volume key event decision. `before`/`after` are the
     * STREAM_MUSIC index around the native adjust (-1 when the event was
     * suppressed or the index is unavailable); they show the actual step delta.
     */
    private fun logDecision(keyEvent: KeyEvent, suppressed: Boolean, before: Int, after: Int) {
        val delta = if (before >= 0 && after >= 0) after - before else Int.MIN_VALUE
        logger.debug(
            "volume key: action=${if (keyEvent.action == KeyEvent.ACTION_DOWN) "DOWN" else "UP"}" +
                " code=${keyEvent.keyCode} repeat=${keyEvent.repeatCount}" +
                " decision=${if (suppressed) "SUPPRESS" else "pass"}" +
                " musicIndex=$before->$after delta=${if (delta == Int.MIN_VALUE) "n/a" else delta}"
        )
    }

    /** Current STREAM_MUSIC volume index via AudioSystem, or -1 on failure. */
    private fun currentMusicVolumeIndex(): Int = try {
        val audioSystemClass = Class.forName("android.media.AudioSystem")
        audioSystemClass.getMethod("getStreamVolume", Int::class.javaPrimitiveType)
            .invoke(null, STREAM_MUSIC) as? Int ?: -1
    } catch (_: Throwable) {
        -1
    }

    companion object {
        private const val QUEUE_DIAG_HOOK_ID = "volume_key_nonlinear_ikbq_diag"
        private const val STATUS_BAR_HOOK_ID = "volume_key_nonlinear_handle_system_key"
        private const val AUDIO_HOOK_ID = "volume_key_nonlinear_handle_volume_key"

        /** android.media.AudioManager.STREAM_MUSIC */
        private const val STREAM_MUSIC = 3

        // Repeat cadence is ~50ms, so 20 repeats ≈ 1s of holding.
        private const val TIER_1_REPEAT = 20
        private const val TIER_2_REPEAT = 60
        private const val TIER_1_MODULO = 4
        private const val TIER_2_MODULO = 2
    }
}
