[versions]
agp = "9.4.0"
kotlin = "2.3.21"
composeBom = "2025.10.00"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
activity = "1.12.0"
lifecycle = "2.9.4"
savedstate = "1.3.3"
navigationCompose = "2.10.0-alpha05"
navigationEvent = "1.1.1"
miuix = "0.9.3"
miuix-blur = "0.9.3"
libxposedApi = "102.0.0"
commonmark = "0.24.0"
lunar = "1.7.5"
hiddenApiBypass = "4.3"
gson = "2.10.1"
dexkit = "2.0.6"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigationevent-compose = { group = "androidx.navigationevent", name = "navigationevent-compose", version.ref = "navigationEvent" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-android", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-android", version.ref = "lifecycle" }
androidx-savedstate = { group = "androidx.savedstate", name = "savedstate-android", version.ref = "savedstate" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
miuix-android = { group = "top.yukonga.miuix.kmp", name = "miuix-ui-android", version.ref = "miuix" }
miuix-blur = { group = "top.yukonga.miuix.kmp", name = "miuix-blur-android", version.ref = "miuix-blur" }
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
lunar = { group = "cn.6tail", name = "lunar", version.ref = "lunar" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenApiBypass" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposedApi" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "libxposedApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

